// all attribute
export const ALL_ATTRIBUTE_REQUEST = 'ALL_ATTRIBUTE_REQUEST'
export const ALL_ATTRIBUTE_SUCCESS = 'ALL_ATTRIBUTE_SUCCESS'
export const ALL_ATTRIBUTE_FAIL = 'ALL_ATTRIBUTE_FAIL'


// create attribute
export const CREATE_ATTRIBUTE_REQUEST = 'CREATE_ATTRIBUTE_REQUEST'
export const CREATE_ATTRIBUTE_SUCCESS = 'CREATE_ATTRIBUTE_SUCCESS'
export const CREATE_ATTRIBUTE_FAIL = 'CREATE_ATTRIBUTE_FAIL'
export const ATTRIBUTE_RESET = 'ATTRIBUTE_RESET'


// Delete attribute
export const  DELETE_ATTRIBUTE_REQUEST ="DELETE_ATTRIBUTE_REQUEST";
export const  DELETE_ATTRIBUTE_SUCCESS ="DELETE_ATTRIBUTE_SUCCESS";
export const  DELETE_ATTRIBUTE_FAIL ="DELETE_ATTRIBUTE_FAIL";
export const  DELETE_ATTRIBUTE_RESET ="DELETE_ATTRIBUTE_RESET";


// Delete attribute values
export const  DELETE_ATTRIBUTE_VALUES_REQUEST ="DELETE_ATTRIBUTE_VALUES_REQUEST";
export const  DELETE_ATTRIBUTE_VALUES_SUCCESS ="DELETE_ATTRIBUTE_VALUES_SUCCESS";
export const  DELETE_ATTRIBUTE_VALUES_FAIL ="DELETE_ATTRIBUTE_VALUES_FAIL";
export const  DELETE_ATTRIBUTE_VALUES_RESET ="DELETE_ATTRIBUTE_VALUES_RESET";





// clear error
export const CLEAR_ERRORS ="CLEAR_ERRORS";


    