// all brand
export const ALL_BRAND_REQUEST = 'ALL_BRAND_REQUEST'
export const ALL_BRAND_SUCCESS = 'ALL_BRAND_SUCCESS'
export const ALL_BRAND_FAIL = 'ALL_BRAND_FAIL'


// create brand
export const CREATE_BRAND_REQUEST = 'CREATE_BRAND_REQUEST'
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS'
export const CREATE_BRAND_FAIL = 'CREATE_BRAND_FAIL'
export const BRAND_RESET = 'BRAND_RESET'

// update brand
export const UPDATE_BRAND_REQUEST = 'UPDATE_BRAND_REQUEST'
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS'
export const UPDATE_BRAND_FAIL = 'UPDATE_BRAND_FAIL'
export const UPDATE_BRAND_RESET = 'UPDATE_BRAND_RESET'



// brand details
export const BRAND_DETAILS_REQUEST ="BRAND_DETAILS_REQUEST";
export const BRAND_DETAILS_SUCCESS ="BRAND_DETAILS_SUCCESS";
export const BRAND_DETAILS_FAIL ="BRAND_DETAILS_FAIL";



// Delete brand
export const  DELETE_BRAND_REQUEST ="DELETE_BRAND_REQUEST";
export const  DELETE_BRAND_SUCCESS ="DELETE_BRAND_SUCCESS";
export const  DELETE_BRAND_FAIL ="DELETE_BRAND_FAIL";
export const  DELETE_BRAND_RESET ="DELETE_BRAND_RESET";





// clear error
export const CLEAR_ERRORS ="CLEAR_ERRORS";

