// all COLORS
export const ALL_COLORS_REQUEST = 'ALL_COLORS_REQUEST'
export const ALL_COLORS_SUCCESS = 'ALL_COLORS_SUCCESS'
export const ALL_COLORS_FAIL = 'ALL_COLORS_FAIL'


// create COLORS
export const CREATE_COLORS_REQUEST = 'CREATE_COLORS_REQUEST'
export const CREATE_COLORS_SUCCESS = 'CREATE_COLORS_SUCCESS'
export const CREATE_COLORS_FAIL = 'CREATE_COLORS_FAIL'
export const COLORS_RESET = 'COLORS_RESET'


// Delete COLORS
export const  DELETE_COLORS_REQUEST ="DELETE_COLORS_REQUEST";
export const  DELETE_COLORS_SUCCESS ="DELETE_COLORS_SUCCESS";
export const  DELETE_COLORS_FAIL ="DELETE_COLORS_FAIL";
export const  DELETE_COLORS_RESET ="DELETE_COLORS_RESET";




// clear error
export const CLEAR_ERRORS ="CLEAR_ERRORS";


    