export const ALL_PRODUCT_REQUEST ="ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS ="ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL ="ALL_PRODUCT_FAIL";


// Delete Product
export const  DELETE_PRODUCT_REQUEST ="DELETE_PRODUCT_REQUEST";
export const  DELETE_PRODUCT_SUCCESS ="DELETE_PRODUCT_SUCCESS";
export const  DELETE_PRODUCT_FAIL ="DELETE_PRODUCT_FAIL";
export const  DELETE_PRODUCT_RESET ="DELETE_PRODUCT_RESET";







// product details
export const PRODUCT_DETAILS_REQUEST ="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS ="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL ="PRODUCT_DETAILS_FAIL";








export const CLEAR_ERRORS ="CLEAR_ERRORS";

