export const ALL_SUPPLIER_REQUEST ="ALL_SUPPLIER_REQUEST";
export const ALL_SUPPLIER_SUCCESS ="ALL_SUPPLIER_SUCCESS";
export const ALL_SUPPLIER_FAIL ="ALL_SUPPLIER_FAIL";


// Delete supplier
export const  DELETE_SUPPLIER_REQUEST ="DELETE_SUPPLIER_REQUEST";
export const  DELETE_SUPPLIER_SUCCESS ="DELETE_SUPPLIER_SUCCESS";
export const  DELETE_SUPPLIER_FAIL ="DELETE_SUPPLIER_FAIL";
export const  DELETE_SUPPLIER_RESET ="DELETE_SUPPLIER_RESET";


// supplier details
export const SUPPLIER_DETAILS_REQUEST ="SUPPLIER_DETAILS_REQUEST";
export const SUPPLIER_DETAILS_SUCCESS ="SUPPLIER_DETAILS_SUCCESS";
export const SUPPLIER_DETAILS_FAIL ="SUPPLIER_DETAILS_FAIL";


// supplier complete details
export const SUPPLIER_COMPLETE_DETAILS_REQUEST ="SUPPLIER_COMPLETE_DETAILS_REQUEST";
export const SUPPLIER_COMPLETE_DETAILS_SUCCESS ="SUPPLIER_COMPLETE_DETAILS_SUCCESS";
export const SUPPLIER_COMPLETE_DETAILS_FAIL ="SUPPLIER_COMPLETE_DETAILS_FAIL";


export const CLEAR_ERRORS ="CLEAR_ERRORS";