export const ALL_USER_REQUEST ="ALL_USER_REQUEST";
export const ALL_USER_SUCCESS ="ALL_USER_SUCCESS";
export const ALL_USER_FAIL ="ALL_USER_FAIL";


// Delete supplier
export const  DELETE_USER_REQUEST ="DELETE_USER_REQUEST";
export const  DELETE_USER_SUCCESS ="DELETE_USER_SUCCESS";
export const  DELETE_USER_FAIL ="DELETE_USER_FAIL";
export const  DELETE_USER_RESET ="DELETE_USER_RESET";


// supplier details
export const USER_DETAILS_REQUEST ="USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS ="USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL ="USER_DETAILS_FAIL";


// supplier complete details
export const USER_COMPLETE_DETAILS_REQUEST ="USER_COMPLETE_DETAILS_REQUEST";
export const USER_COMPLETE_DETAILS_SUCCESS ="USER_COMPLETE_DETAILS_SUCCESS";
export const USER_COMPLETE_DETAILS_FAIL ="USER_COMPLETE_DETAILS_FAIL";


export const CLEAR_ERRORS ="CLEAR_ERRORS";