export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER_REQUEST'
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SELLER_SUCCESS'
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL'

export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const LOGOUT_FAIL ="LOGOUT_FAIL";

export const LOAD_SELLER_REQUEST ="LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS ="LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL ="LOAD_SELLER_FAIL";



export const GET_SELLER_DETAILS_REQUEST = "GET_SELLER_DETAILS_REQUEST";
export const GET_SELLER_DETAILS_SUCCESS = "GET_SELLER_DETAILS_SUCCESS";
export const GET_SELLER_DETAILS_RESET = "GET_SELLER_DETAILS_RESET";
export const GET_SELLER_DETAILS_FAIL = "GET_SELLER_DETAILS_FAIL";

export const UPDATE_SELLER_DETAILS_REQUEST = "UPDATE_SELLER_DETAILS_REQUEST";
export const UPDATE_SELLER_DETAILS_SUCCESS = "UPDATE_SELLER_DETAILS_SUCCESS";
export const UPDATE_SELLER_DETAILS_FAIL = "UPDATE_SELLER_DETAILS_FAIL";
export const UPDATE_SELLER_DETAILS_RESET = "UPDATE_SELLER_DETAILS_RESET";



export const UPDATE_SELLER_BANK_DETAILS_REQUEST = "UPDATE_SELLER_BANK_DETAILS_REQUEST";
export const UPDATE_SELLER_BANK_DETAILS_SUCCESS = "UPDATE_SELLER_BANK_DETAILS_SUCCESS";
export const UPDATE_SELLER_BANK_DETAILS_FAIL = "UPDATE_SELLER_BANK_DETAILS_FAIL";
export const UPDATE_SELLER_BANK_DETAILS_RESET = "UPDATE_SELLER_BANK_DETAILS_RESET";

export const UPDATE_SELLER_ADDRESS_DETAILS_REQUEST = "UPDATE_SELLER_ADDRESS_DETAILS_REQUEST";
export const UPDATE_SELLER_ADDRESS_DETAILS_SUCCESS = "UPDATE_SELLER_ADDRESS_DETAILS_SUCCESS";
export const UPDATE_SELLER_ADDRESS_DETAILS_FAIL = "UPDATE_SELLER_ADDRESS_DETAILS_FAIL";
export const UPDATE_SELLER_ADDRESS_DETAILS_RESET = "UPDATE_SELLER_ADDRESS_DETAILS_RESET";


export const UPDATE_SELLER_SHOP_DETAILS_REQUEST = "UPDATE_SELLER_SHOP_DETAILS_REQUEST";
export const UPDATE_SELLER_SHOP_DETAILS_SUCCESS = "UPDATE_SELLER_SHOP_DETAILS_SUCCESS";
export const UPDATE_SELLER_SHOP_DETAILS_FAIL = "UPDATE_SELLER_SHOP_DETAILS_FAIL";
export const UPDATE_SELLER_SHOP_DETAILS_RESET = "UPDATE_SELLER_SHOP_DETAILS_RESET";


export const CLEAR_ERRORS ="CLEAR_ERRORS";
